# Generated by Django 3.1.5 on 2021-02-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210217_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='region',
            field=models.OneToOneField(default=225, on_delete=django.db.models.deletion.DO_NOTHING, to='main.region'),
        ),
    ]
