# Generated by Django 3.1.4 on 2020-12-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('site_age_concurency', models.IntegerField(default=0)),
                ('site_stem_concurency', models.IntegerField(default=0)),
                ('site_volume_concurency', models.IntegerField(default=0)),
                ('site_backlinks_concurency', models.IntegerField(default=0)),
                ('site_total_concurency', models.FloatField(default=0)),
                ('direct_upscale', models.FloatField(default=0)),
            ],
        ),
    ]
