# Generated by Django 3.1.4 on 2021-02-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='direct_concurency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='seo_concurency',
            field=models.IntegerField(default=0),
        ),
    ]
