# Generated by Django 3.1.7 on 2021-05-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestqueue',
            old_name='request_id',
            new_name='request',
        ),
    ]
