# Generated by Django 3.1.4 on 2020-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_payload_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatement',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('ordered_requests', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
