# Generated by Django 3.1.4 on 2021-02-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210202_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='direct_concurency',
            new_name='site_direct_concurency',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='seo_concurency',
            new_name='site_seo_concurency',
        ),
    ]
