# Generated by Django 3.1.7 on 2021-05-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210525_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.RemoveField(
            model_name='orderdata',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
