# Generated by Django 3.1.4 on 2020-12-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201230_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('site_age_concurency', models.IntegerField(default=0)),
                ('site_stem_concurency', models.IntegerField(default=0)),
                ('site_volume_concurency', models.IntegerField(default=0)),
                ('site_backlinks_concurency', models.IntegerField(default=0)),
                ('site_total_concurency', models.FloatField(default=0)),
                ('direct_upscale', models.FloatField(default=0)),
            ],
        ),
    ]
