# Generated by Django 3.1.4 on 2020-12-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestQueue',
            fields=[
                ('request', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
