# Generated by Django 3.1.5 on 2021-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_requestqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
