# Generated by Django 3.1.7 on 2021-05-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210526_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='posts',
        ),
        migrations.AddField(
            model_name='ticketpost',
            name='ticket',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.ticket'),
            preserve_default=False,
        ),
    ]
