# Generated by Django 3.1.7 on 2021-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210527_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpost',
            name='order',
        ),
    ]
