# Generated by Django 3.1.5 on 2021-02-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210205_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='progress',
            field=models.SmallIntegerField(default=0),
        ),
    ]
