# Generated by Django 3.1.5 on 2021-02-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_orderstatus_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
