# Generated by Django 3.1.5 on 2021-02-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orderstatus_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='ordered_keywords_amount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
