# Generated by Django 3.1.5 on 2021-02-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_orderstatus_ordered_keywords_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='ordered_keywords',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='orders_amount',
            field=models.IntegerField(default=0),
        ),
    ]
