# Generated by Django 3.1.5 on 2021-02-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210205_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=0)),
                ('ticket_author', models.CharField(max_length=25)),
                ('ticket_post_author', models.SmallIntegerField(default=0)),
                ('ticket_post_text', models.TextField(default='')),
                ('ticket_post_order', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
