# Generated by Django 3.1.5 on 2021-02-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_ticketpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=15)),
                ('opened', models.DateTimeField()),
                ('closed', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='ticketpost',
            old_name='ticket_id',
            new_name='ticked_id',
        ),
        migrations.RemoveField(
            model_name='ticketpost',
            name='ticket_author',
        ),
    ]
