# Generated by Django 3.1.5 on 2021-02-06 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210206_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='opened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
