# Generated by Django 3.1.5 on 2021-02-07 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210206_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticketpost',
            name='ticket_post_author',
            field=models.CharField(default='', max_length=25),
        ),
    ]
