# Generated by Django 3.1.5 on 2021-02-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210207_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
