# Generated by Django 3.1.5 on 2021-02-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210208_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
