# Generated by Django 3.1.5 on 2021-02-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210210_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='request_id',
            new_name='request',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ticketpost',
            old_name='ticked_id',
            new_name='ticket',
        ),
    ]
