# Generated by Django 3.1.5 on 2021-02-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210210_0649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='id',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request',
            new_name='request_text',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='ticketpost',
            old_name='id',
            new_name='ticket_post_id',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='id',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='UserStatement',
        ),
    ]
