# Generated by Django 3.1.5 on 2021-02-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210210_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket',
            new_name='ticket_id',
        ),
    ]
