# Generated by Django 3.1.5 on 2021-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210210_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketpost',
            name='ticket_post_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
