# Generated by Django 3.1.5 on 2021-02-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_orderstatus_user_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_ticket_id',
            field=models.IntegerField(default=1),
        ),
    ]
