# Generated by Django 3.1.5 on 2021-02-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_userdata_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='region',
            field=models.ForeignKey(default=255, on_delete=django.db.models.deletion.DO_NOTHING, to='main.region'),
        ),
    ]
