# Generated by Django 3.1.5 on 2021-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210217_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
