# Generated by Django 3.1.5 on 2021-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_request_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestqueue',
            name='geo',
            field=models.IntegerField(default=255),
        ),
    ]
