# Generated by Django 3.1.5 on 2021-02-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_requestqueue_geo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestQueue',
        ),
    ]
