# Generated by Django 3.1.5 on 2021-02-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_requestqueue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandledXml',
        ),
    ]
