# Generated by Django 3.1.5 on 2021-02-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_delete_handledxml'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandledXml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('xml', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('geo', models.IntegerField(default=225)),
            ],
        ),
    ]
