# Generated by Django 3.1.5 on 2021-02-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_handledxml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='geo',
            new_name='region_id',
        ),
    ]
