# Generated by Django 3.1.5 on 2021-02-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210219_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='region_id',
        ),
        migrations.AddField(
            model_name='request',
            name='region',
            field=models.ForeignKey(default=255, on_delete=django.db.models.deletion.DO_NOTHING, to='main.region'),
        ),
    ]
