# Generated by Django 3.1.5 on 2021-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20210223_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_views',
            field=models.IntegerField(default=0),
        ),
    ]
