# Generated by Django 3.1.5 on 2021-02-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_request_request_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_views',
            field=models.CharField(max_length=100),
        ),
    ]
