# Generated by Django 3.1.5 on 2021-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210225_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_views',
            field=models.IntegerField(default=0),
        ),
    ]
