# Generated by Django 3.1.5 on 2021-03-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20210225_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperSites',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('unique_backlinks', models.IntegerField(default=0)),
                ('total_backlinks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='average_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='average_total_backlinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='average_unique_backlinks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='average_volume',
            field=models.IntegerField(default=0),
        ),
    ]
