# Generated by Django 3.1.5 on 2021-03-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20210308_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
