# Generated by Django 3.1.5 on 2021-03-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20210309_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='group',
            new_name='domain_group',
        ),
    ]
