# Generated by Django 3.1.7 on 2021-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_request_vital_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='vital_sites_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
