# Generated by Django 3.1.7 on 2021-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_request_vital_sites_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
