# Generated by Django 3.1.7 on 2021-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20210324_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='handledxml',
            name='refresh_timer',
            field=models.IntegerField(default=225),
        ),
    ]
