# Generated by Django 3.1.7 on 2021-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_handledxml_refresh_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestqueue',
            name='is_recheck',
            field=models.BooleanField(default=False),
        ),
    ]
