# Generated by Django 3.1.7 on 2021-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20210417_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_direct_final',
            field=models.SmallIntegerField(default=0),
        ),
    ]
