# Generated by Django 3.1.7 on 2021-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_request_is_direct_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_text',
            field=models.CharField(max_length=150),
        ),
    ]
