# Generated by Django 3.1.7 on 2021-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20210421_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='vital_sites',
            field=models.CharField(default='', max_length=150),
        ),
    ]
